AMDAPPSDKROOT=/home/olehp/AMDAPPSDK-2.9-1/
OPENCL_VENDOR_PATH=/home/olehp/AMDAPPSDK-2.9-1/etc/OpenCL/vendors/
OPENCL_LD_LIBRARY_PATH=/usr/lib32:/home/olehp/AMDAPPSDK-2.9-1/lib/x86_64/:/home/olehp/AMDAPPSDK-2.9-1/lib/x86/

INCLUDE_DIRS += $(AMDAPPSDKROOT)include
LIBS_DIRS += $(AMDAPPSDKROOT)lib/x86_64
LIBS += -lOpenCL
VALGRIND_OPTS += --suppressions=ocl.supp

LAUNCH_OPTS += LD_LIBRARY_PATH=$(OPENCL_LD_LIBRARY_PATH)



 

